apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
  labels:
    app: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealership
  template:
    metadata:
      labels:
        app: dealership
    spec:
      containers:
        - name: dealership
          image: us.icr.io/sn-labs-lokesh_s2k/dealership:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
