services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db_container
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  django_web:
    build:
      context: .
      dockerfile: Dockerfile  # make sure this Dockerfile is in the same dir
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - node_api



  node_api:
    build:
      context: ./database
    container_name: node_api
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db
      - sentiment_service
    volumes:
      - ./database:/usr/src/app
    working_dir: /usr/src/app
    command: node app.js

  sentiment_service:
    build:
      context: ./djangoapp/microservices
    container_name: sentiment_container
    ports:
      - "5050:5000"
    environment:
      - FLASK_ENV=development

volumes:
  mongo_data: {}
